# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.24.0"
stylua = "johnnymorganz/stylua@0.16.1"
wally-package-types = "johnnymorganz/wally-package-types@1.2.1"
